### ISSUE TITLE
【内测报告】Helldefender

### ISSUE THREAD

**Issue by Helldefender** [lanshan-studio/wecqupt#106]
* 登录问题：完善信息后首页没有刷新（或者说完善信息无效）
* 考试安排：点击每个item右侧的button很难展开详情，
* 资讯：附件无法预览
*  一卡通近十次消费情况建议改成近十次的消费金额，也可以设置一上一下两个金额（消费金额和余额）
* 首页：下拉刷新没有特效
* 物业保修和学费信息加载失败（学生查询只出现过一次）
* 保修申请：界面输入框的提示文字在选中时颜色会变得很怪？（只出现过一次），输入法的弹出给入一种一顿的感觉。具体内容只有在点击提示时才会弹出输入法
* 借阅信息里无法查看以前借了什么书吗？
* 空教室：若空教室数目超过一行则第一行最后一个教室信息不能完全显示
* 成绩查询：可以显示下绩点，而且只能查看一个学期的成绩，可以多把上学期的也显示下撒
* 课表查询：查看他人课表后点击返回键直接退回到首页了，不是应该返回上一个界面吗？item右侧的button点击后还是很难展开详情；在用课表的情况下，切换周数，只是对应课程改变，整个界面没有滑动到初始位置；点击课程会出现对应的学分很惊艳！但位置有点偏。。。
* 关于和反馈页面都还是空白的，这貌似不是个问题。。。
* 输入框是个很讨厌人的东西，在完善信息时填完身份证需要手动上滑，才会消失，可以来个完成的按钮
* 打开失败 已在前台运行 ？一脸懵逼的我，小程序怎么才算退出？

**Comment by mcc108** [comment]
1、登录问题：已发现该问题 #80 
2、考试安排：这个应该优化下 #111
3、资讯附件：已发现该问题 #90 
4、一卡通： 有空了改成一上一下两个金额（消费金额和余额）吧   #112
5、首页下拉刷新特效是微信自带的，有几个点在下拉那儿，很快就加载好了。
6、物业保修和学费信息加载失败，后端看一下 @xiaoliuhao 
7、弹出输入法这个是微信小程序自带的，有很多限制，有空了再看怎么想办法解决下
8、借阅信息里无法查看以前借了什么书。。。  #107 
9、应该会在某些手机上出现，建个issues #113 空教室数目超过一行则第一行最后一个教室信息不能完全显示 
10、成绩查询数据能查的比较少，下一个大版本协调数据更新下
11、课表查询和学生查询来回切换可能会导致页面太多而崩溃，见#74
12、关于和反馈页面未完成 #67 #68 
13、输入框问题有个同学找了个好办法解决：#108
14、目前微信小程序还没正式发布，也不知道它到底怎么确定前台还是后台的，  退出的话应该是点右上角里面有个离开，才是真正的退出吧...

**Comment by xiaoliuhao** [comment]
6.低年级学费加载失败已修复. 报修加载失败...是没有报修过加载失败吗?

**Comment by mcc108** [comment]
考试安排：感觉没有问题呀，能具体描述吗 #111
