### ISSUE TITLE
【内测报告】

### ISSUE THREAD

**Issue by fbl861543** [lanshan-studio/wecqupt#109]
登录
1.	切换绑定时输入的账号和密码都是对的，但仍显示错误
2.	帮助界面为啥账号那一栏句号占据了一行
3.	反馈的界面是空的
4.关于的界面是空的

课表查询
1.	查询单节课时具体信息出现的很慢，感觉是卡着的
2.	学生名单中个人信息里面专业名没有显示专业名

成绩查询
1.只能显示上学期的成绩不能切换
2.	没有专业排名和绩点，综合成绩，综合排名

考试安排
感觉很好用

空教室
可以增加一项新功能，查询教室可坐多少人吗？

一卡通
1.一卡通图片不是很好看
2.	可以将“点击上图查看对应消费详情”做的明显一点
3.更新好慢。今天都12月1号了，消费记录还是11月29号的

学费信息
加载失败

电费查询
1.	更新太慢，现在是12月1号但是显示的是7月25号

物业报修
服务申报中已经填了服务类型、项目、区域申报内容就不用填了吧

资讯
头条都不能加载出来

**Comment by fbl861543** [comment]
登录

切换绑定时输入的账号和密码都是对的，但仍显示错误
帮助界面为啥账号那一栏句号占据了一行
反馈的界面是空的
4.关于的界面是空的
课表查询

查询单节课时具体信息出现的很慢，感觉是卡着的
学生名单中个人信息里面专业名没有显示专业名
成绩查询
1.只能显示上学期的成绩不能切换
2.	没有专业排名和绩点，综合成绩，综合排名

考试安排
感觉很好用

空教室
可以增加一项新功能，查询教室可坐多少人吗？

一卡通
1.一卡通图片不是很好看
2.	可以将“点击上图查看对应消费详情”做的明显一点
3.更新好慢。今天都12月1号了，消费记录还是11月29号的

学费信息
加载失败

电费查询

更新太慢，现在是12月1号但是显示的是7月25号
物业报修
服务申报中已经填了服务类型、项目、区域申报内容就不用填了吧

资讯
头条都不能加载出来

**Comment by mcc108** [comment]
见 #96
