### ISSUE TITLE
【内测报告】黄容测试结果

### ISSUE THREAD

**Issue by adoblove** [lanshan-studio/wecqupt#117]
学生账号登录
1.第一次登录时，提完善个人数据，我已完善寝室号和身份证后6位，但在第一次使用成绩查询时，又提示需填写身份证后6位
2.空教室查询：教室列表左右滑动，最好不滑动，可以换行
3.首页借阅信息：已借天数计算错误。显示0天。
4.学费信息不能查询，提示参数错误。
5.电费查询没有结果
6.物业报修，提交了测试的工单，没有显示申请记录
老师账号登录：
1.统一身份 认证接口里的用户基本信息没有取到，不能显示。
2.登录时完善信息，如果是教师角色，不需要填写宿舍信息，如果取教务数据需要，可以输入身份证后6位。
3.主页上：课表、一卡通、借阅数据都不正确
4.借阅数据显示了上一个同学的数据
5.很多功能不能使用，提示未绑定。应该不正确

**Comment by mcc108** [comment]
学生账号登录的问题基本都解决了，在下一个版本会更新。
老师账号登录的问题还在解决中。#116
