### ISSUE TITLE
【刘堂臣】按班级查询的问题

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#193]
学生查询进去后，查询某个班，会加载班级所有人名单，但此时不退出，直接再次查询另一个班，这时就有问题出现了，不能加载出此班所有人名单，只有部分人名单

---
用户信息
用户名：刘堂臣（本科生-刘堂臣-2015211939）
手机型号：vivo X5S L（360x567）
微信版本号：6.3.31

**Comment by mcc108** [comment]
DONE
