### ISSUE TITLE
【Vincenzo】考试查询，反馈功能

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#202]
考试查询，软件技术基础这门课，我任课老师是耿道渠。
反馈功能，反馈输入框不灵敏，要点很多下。

---
用户信息
用户名：Vincenzo（本科生-刘文栖-2014212818）
手机型号：NX529J（360x567）
微信版本号：6.3.31

**Comment by mcc108** [comment]
输入框不灵敏，坐等看微信能否解决 #203
