### ISSUE TITLE
【Misic Demone】ios课表详情两节重课与三节重课表现不一致

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#230]
这个版本三节重课的时候划下面的时候不再存在滑动穿透，但是两节重课的时候还是会穿透。(只有一节课的时候还是和以前一样会穿透。)

---
用户信息
用户名：Misic Demone（本科生-宋思辰-2014211418）
手机型号：iPhone 6s<iPhone8,1>（ios - 375x603）
微信版本号：6.5.2

![img](http://wecqupt.congm.in/Fv-qS_PSPRTKhJMwMxgLyjUUxGfV?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/V2Xph43pgq4=/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

![img](http://wecqupt.congm.in/FjawJSK-ROXz2mLw-XMDIcEKLB2c?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/V2Xph43pgq4=/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

**Comment by mcc108** [comment]
bindtouchstart导致的穿透滑动
但改为catchtouchstart后又会导致navigator无法点击。

**Comment by mcc108** [comment]
利用catchtouchmove解决了
