### ISSUE TITLE
【刘浩】新闻预览附件问题

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#248]
预览同一个附件会多次下载

---
**用户信息**
用户名：刘浩（本科生-刘浩-2014211750）
手机型号：M3s（android - 360x570）
微信版本号：6.5.3
We重邮版本号：v0.1.0

![img](http://wecqupt.congm.in/FqkS1EYipfpR5Viip8uLO7IERLxn?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/V2Xph43pgq4=/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

![img](http://wecqupt.congm.in/Fg8H9u9VoIwubBGA-xe8quqfJdiS?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/V2Xph43pgq4=/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

**Comment by mcc108** [comment]
万一是被分成了这几个文件了呢？0 。0
