### ISSUE TITLE
没有测试帐号可以绑定,很多功能用不了,望提供一下测试帐号

### ISSUE THREAD

**Issue by dengzhuqing** [lanshan-studio/wecqupt#251]
![image](https://cloud.githubusercontent.com/assets/24959939/21720174/b74a1e9e-d45c-11e6-8c56-c09c16fc0820.png)
![image](https://cloud.githubusercontent.com/assets/24959939/21720181/bc30a784-d45c-11e6-8b64-71643911c6b7.png)
![image](https://cloud.githubusercontent.com/assets/24959939/21720188/c71a8c46-d45c-11e6-836a-3abad5b5f596.png)

**Comment by mcc108** [comment]
以后应该会考虑加入测试帐号。
