### ISSUE TITLE
【ともえ】学生查询

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#252]
查询其他同学，点进她的课表返回就退回了首页，应该退回到上一个页面的吧

---
**用户信息**
用户名：ともえ（本科生-陈梦圆-2015211827）
手机型号：MI MAX（android - 392.72726x630.1818）
微信版本号：6.5.3
We重邮版本号：v0.1.0

**Comment by mcc108** [comment]
目前是为了防止课表和学生查询两个页面来回切换导致页面栈过多。
以后微信应该会更新关闭自定栈的api
