### ISSUE TITLE
【ともえ】物业维修

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#253]
刚刚建立的维修申请，状态显示未审核，为什么响应时间显示120分以上？

---
**用户信息**
用户名：ともえ（本科生-陈梦圆-2015211827）
手机型号：MI MAX（android - 392.72726x630.1818）
微信版本号：6.5.3
We重邮版本号：v0.1.0

**Comment by mcc108** [comment]
有没有图？
