### ISSUE TITLE
【ともえ】物业报修

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#254]
物业报修时填了具体地址，但是物业打电话说他们那边没有收到具体地址，只能看到是学生公寓区

---
**用户信息**
用户名：ともえ（本科生-陈梦圆-2015211827）
手机型号：MI MAX（android - 392.72726x630.1818）
微信版本号：6.5.3
We重邮版本号：v0.1.0

**Comment by mcc108** [comment]
了解
