### ISSUE TITLE
【carlsonlin】很赞

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#257]
给力

---
**用户信息**
用户名：carlsonlin
手机型号：SM-G9280（android - 411.42856x659.4286）
微信版本号：6.5.3
We重邮版本号：v0.1.1

![img](http://wecqupt.congm.in/FkHiaO5KDHFB9P104De2Gr6r8KKE?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/V2Xph43pgq4=/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

**Comment by mcc108** [comment]
😁
