### ISSUE TITLE
【啊弥台】怎么把你从置顶中取消？

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#261]
宝宝就是试了试这个传说的小程序，现。在好了，发呆了，还取消不了了。哭

---
**用户信息**
用户名：啊弥台
手机型号：Redmi Note 3（android - 360x572）
微信版本号：6.5.3
We重邮版本号：v0.1.1

**Comment by mcc108** [comment]
过一段时间就会自己掉的
