### ISSUE TITLE
【乞力马扎罗の雪】无法正常退出

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#262]
按退出键后无法返回微信上级菜单，而是直接切换到桌面，并且小程序栏中图标无法显示，

---
**用户信息**
用户名：乞力马扎罗の雪（本科生-苏春晓-2016211632）
手机型号：VIE-AL10（android - 392.72726x586.1818）
微信版本号：6.5.3
We重邮版本号：v0.1.1

**Comment by mcc108** [comment]
小程序 的进程是和 微信 分离开的，所有小程序是相对独立的，切换到桌面，应该属于正常现象吧
