### ISSUE TITLE
【Z X Y】成绩查询

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#263]
成绩查询为空，求改进

---
**用户信息**
用户名：Z X Y（研究生-张勋杨-S160231087）
手机型号：iPhone 6 Plus<iPhone7,1>（ios - 414x672）
微信版本号：6.5.3
We重邮版本号：v0.1.1

![img](http://wecqupt.congm.in/FrRA9oCP37X8YYik-7qgQ_O2akTr?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/V2Xph43pgq4=/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

**Comment by mcc108** [comment]
研究生用户可能无法查询成绩，
我们会修改一下这个提醒。

**Comment by mcc108** [comment]
以后会考虑兼容一下 #277
