### ISSUE TITLE
【Z X Y】学生查询

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#264]
学生查询里无法搜索研究生同学

---
**用户信息**
用户名：Z X Y（研究生-张勋杨-S160231087）
手机型号：iPhone 6 Plus<iPhone7,1>（ios - 414x672）
微信版本号：6.5.3
We重邮版本号：v0.1.1

**Comment by mcc108** [comment]
抱歉。暂时不支持研究生同学

**Comment by mcc108** [comment]
以后会考虑兼容一下 #277
