### ISSUE TITLE
【黎志航】反馈

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#265]
反馈

---
**用户信息**
用户名：黎志航
手机型号：iPhone 6<iPhone7,2>（ios - 375x603）
微信版本号：6.5.3
We重邮版本号：v0.1.1

![img](http://wecqupt.congm.in/Fvsx7fE7O6uYRJ59LIBOGKJTc6PZ?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/V2Xph43pgq4=/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

**Comment by mcc108** [comment]
了解到这个bug，我们会尽快修复
