### ISSUE TITLE
【 王子木】给你们点赞！

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#266]
你们是哪个团队呀？真是棒！！！！！！为你们点赞！！！！！！！！！！

---
**用户信息**
用户名： 王子木（本科生-李琛-2013211216）
手机型号：MI MAX（android - 392.72726x630.1818）
微信版本号：6.5.3
We重邮版本号：v0.1.1

**Comment by mcc108** [comment]
蓝山工作室

Thx  😁
