### ISSUE TITLE
【托塔的🐼~^o^~】程序置顶

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#268]
程序一开关机之后，置顶就没有了

---
**用户信息**
用户名：托塔的🐼~^o^~（本科生-李婧-2015213628）
手机型号：PRO 6（android - 360x570）
微信版本号：6.5.3
We重邮版本号：v0.1.1

**Comment by mcc108** [comment]
置顶是暂时的哦，只是为了方便聊天。
你可以添加到桌面
