### ISSUE TITLE
【蛋炒饭】借阅信息有Bug

### ISSUE THREAD

**Issue by lanshan-admin** [Lanshan-Studio/wecqupt#269]
如图，前四本书是12.14归还的，但是却显示为借阅

---
**用户信息**
用户名：蛋炒饭（本科生-胡强-2015214650）
手机型号：Redmi 3（android - 360x567）
微信版本号：6.5.3
We重邮版本号：v0.1.1

![img](http://wecqupt.congm.in/Fu1ZeIIVPfemxVBWsoeFUx6CSko1?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/V2Xph43pgq4=/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

**Comment by mcc108** [comment]
我们看看这个问题

**Comment by mcc108** [comment]
检查看还有这个问题吗？
