### ISSUE TITLE
【蛋炒饭】借阅信息BUG

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#270]
如图

---
**用户信息**
用户名：蛋炒饭（本科生-胡强-2015214650）
手机型号：Redmi 3（android - 360x567）
微信版本号：6.5.3
We重邮版本号：v0.1.1

![img](http://wecqupt.congm.in/FhXydOCaCBJPtJmralxJFw8fw_JO?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/V2Xph43pgq4=/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

**Comment by mcc108** [comment]
见#269
