### ISSUE TITLE
【泓】匿名

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#271]
图书馆的借阅信息好像更新有点慢，还书日期好像不对

---
**用户信息**
用户名：泓（本科生-唐泓-2014212653）
手机型号：MI 5（android - 360x572）
微信版本号：6.5.3
We重邮版本号：v0.1.1

**Comment by mcc108** [comment]
了解到这个问题

**Comment by mcc108** [comment]
可以检测下现在是否还有问题
