### ISSUE TITLE
【Ricardo】学生查询

### ISSUE THREAD

**Issue by Ricardo-Ke** [lanshan-studio/wecqupt#272]
[1] input框聚焦后有一个闪动，placeholder下移了1px左右(目测)。
[2] 希望增加校历功能

-----------------

用户信息
用户名：樊珂 2014212160
手机型号：Mi 3W<MIUI 8.1.3>
微信版本号：6.5.3
We重邮版本号：v0.1.1
![screenshot_2017-01-09-11-37-57-852_com tencent mm](https://cloud.githubusercontent.com/assets/11808826/21756808/fd061892-d660-11e6-80db-17fadc8f166b.png)

**Comment by mcc108** [comment]
谢谢反馈，
1、这个微信官方的bug，以后应该会官方应该会解决掉
2、校历功能以后的版本会考虑添加的

**Comment by mcc108** [comment]
#278
