### ISSUE TITLE
【谢骥】关于 账号绑定问题

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#274]
1、绑定了3次，每次都显示  绑定成功并跳转到了主页，却 一直加载中
2、如上，绑定了3次，也就是，每次绑定都没有 接受到反馈

---
**用户信息**
用户名：谢骥
手机型号：MX5（android - 360x570）
微信版本号：6.5.3
We重邮版本号：v0.1.1

**Comment by mcc108** [comment]
图#275
我们看一下这个问题

**Comment by mcc108** [comment]
现在应该没有问题了
