### ISSUE TITLE
【谢骥】关于  绑定问题

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#275]
加个图片  

---
**用户信息**
用户名：谢骥
手机型号：MX5（android - 360x570）
微信版本号：6.5.3
We重邮版本号：v0.1.1

![img](http://wecqupt.congm.in/FshUBDquyLAMIKV8RfiD9n0VNwnw?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/V2Xph43pgq4=/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

**Comment by mcc108** [comment]
见#274
