### ISSUE TITLE
【Rye】桌面图标启动慢

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#276]
杀掉所有后台，用桌面图标启动，启动程序慢

---
**用户信息**
用户名：Rye（本科生-罗浩-2014210324）
手机型号：MI 4 LTE（android - 360x568）
微信版本号：6.5.3
We重邮版本号：v0.1.1

**Comment by mcc108** [comment]
这个主要是微信那边的处理，以后他们应该会优化
