### ISSUE TITLE
【阿林小林】隐私问题

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#279]
输入姓名直接可以查别人的课表和考试安排是不是有点不好

---
**用户信息**
用户名：阿林小林（本科生-王林-2015213027）
手机型号：NX549J（android - 360x567）
微信版本号：6.5.3
We重邮版本号：v0.1.1

**Comment by mcc108** [comment]
这两个都是在教务在线上面可以查到的，我们只是做了展示
