### ISSUE TITLE
【谢应涛】首页功能无法使用

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#280]
为啥首页所有项目 都不能使用

---
**用户信息**
用户名：谢应涛（教职工-谢应涛-020519）
手机型号：MI MAX（android - 392.72726x630.1818）
微信版本号：6.5.3
We重邮版本号：v0.1.1

**Comment by mcc108** [comment]
老师，你好。方便的话加We重邮用户反馈QQ群487586022，具体看一下是什么情况。

**Comment by mcc108** [comment]
老师你好，我们会尽快解决这个问题

**Comment by mcc108** [comment]
老师，您好，我们已经解决掉这个问题了，请您再下一个版本v0.1.2We重邮再核实一下这个问题，谢谢~
