### ISSUE TITLE
【梦林】切换绑定同一个账号也提示需要完善寝室信息

### ISSUE THREAD

**Issue by wupengju** [lanshan-studio/wecqupt#282]
切换绑定用户到登录界面绑定已经绑定过的用户，绑定成功后也会提示需要完善信息

---
**用户信息**
用户名：梦林
手机型号：OPPO R6007（android）
微信版本号：6.5.3
We重邮版本号：v0.1.1

**Comment by mcc108** [comment]
目前是这样的。以后的大版本应该会更新掉整个问题，推荐的做法就是不要频繁切换用户。
