### ISSUE TITLE
【封叶】交流，功能完善

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#283]
增加学生互动和加好友，可向学长提问，介绍重邮图书馆网上查看，借阅方法，申请教室途径，各种公文格式，流程，发布教务在线最新动态，新闻，比赛活动等。

---
**用户信息**
用户名：封叶（本科生-宋贵林-2016214549）
手机型号：vivo Y31A（android - 360x569.3333）
微信版本号：6.5.3
We重邮版本号：v0.1.1

**Comment by mcc108** [comment]
以后会考虑增加新功能
