### ISSUE TITLE
【mrl】报修功能

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#284]
物业报修可以上传1张图片。图片保存在你们的服务器上，我这边只接收图片url。

---
**用户信息**
用户名：mrl（教职工-穆仁龙-340222）
手机型号：HUAWEI RIO-AL00（android - 360x520）
微信版本号：6.5.3
We重邮版本号：v0.1.1

**Comment by mcc108** [comment]
是物业报修的详情吗，物业报修的详情目前是只能显示文字的

**Comment by mcc108** [comment]
#320
