### ISSUE TITLE
【李健】课表等信息没有

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#285]
我的课表查询和考试安排都没有，教研室也不对啊

---
**用户信息**
用户名：李健（教职工-李健-090230）
手机型号：MX5（android - 360x570）
微信版本号：6.5.3
We重邮版本号：v0.1.1

![img](http://wecqupt.congm.in/FqONXOHt188f8DocRk3Fq8GxOo3G?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/V2Xph43pgq4=/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

**Comment by mcc108** [comment]
老师您好，感谢反馈
我们查明一下情况。

**Comment by mcc108** [comment]
老师您好，我们已经发现应该是有**重名教师的原因导致**。
我们会与教务处协商，让数据更进去
