### ISSUE TITLE
【mrl】报修列表问题

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#289]
报修的标题是用报修内容来呈现的。进入报修详情页面也没有报修标题。webservice正确返回了报修标题的

---
**用户信息**
用户名：mrl（教职工-穆仁龙-340222）
手机型号：HUAWEI RIO-AL00（android - 360x520）
微信版本号：6.5.3
We重邮版本号：v0.1.1

![img](http://wecqupt.congm.in/Fgjhu_D0FUDo2hMRQxp96T3TVTnS?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/V2Xph43pgq4=/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

**Comment by mcc108** [comment]
老师，你好。
我们会马上核实这个问题的

**Comment by mcc108** [comment]
下个版本将会修复
