### ISSUE TITLE
【嘛园】建议

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#290]
学生查询那里如果加入照片，会很大程度上增加用户及流量，照片不是提取，是用户自愿添加生活照😏 

---
**用户信息**
用户名：嘛园（本科生-郭鑫-2013213661）
手机型号：ZUK Z2131（android - 360x574）
微信版本号：6.5.3
We重邮版本号：v0.1.1

**Comment by mcc108** [comment]
以后会根据实际情况，增加同学间的互动功能
