### ISSUE TITLE
【李雪莲】有bug

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#291]
我绑定了几次，也提醒我说绑定成功，可是就是显示我没有绑定-_-||

---
**用户信息**
用户名：李雪莲
手机型号：HUAWEI TAG-AL00（android - 360x519）
微信版本号：6.5.3
We重邮版本号：v0.1.1

**Comment by mcc108** [comment]
你好我们已经发现这个问题，我们会尽快解决的

**Comment by mcc108** [comment]
现在应该没有问题了
