### ISSUE TITLE
【小风】建议给添加后退按钮

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#292]
建议给添加后退按钮

---
**用户信息**
用户名：小风（教职工-冯成江-340903）
手机型号：HTC D10w（android - 360x568）
微信版本号：6.5.3
We重邮版本号：v0.1.1

**Comment by mcc108** [comment]
老师，您好。
这个是微信小程序自带的功能，我们也不能控制的。
安卓系统是通过的实体返回键进行返回的。
