### ISSUE TITLE
【张慧敏】什么大学可以使用

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#293]
只有重庆邮电大学可以使用吗？账号是什么？

---
**用户信息**
用户名：张慧敏
手机型号：iPhone 6<iPhone7,2>（ios - 375x603）
微信版本号：6.5.3
We重邮版本号：v0.1.1

**Comment by mcc108** [comment]
只有重庆邮电大学可以使用。所以才叫We重邮
