### ISSUE TITLE
【黄容】绑定时账号密码错误的提示语

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#299]
提示账号或密码错误，能不能根据实际情况，明确提示账号错，还是密码错

---
**用户信息**
用户名：黄容（教职工-黄容-0102295）
手机型号：iPhone 6 Plus<iPhone7,1>（ios - 414x672）
微信版本号：6.5.3
We重邮版本号：v0.1.1

**Comment by mcc108** [comment]
不行, 那是统一认证平台来认证的
