### ISSUE TITLE
【TBWYL】一个小bug

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#301]
置顶是个非常好用的功能！但是有个小小的bug在进入类似于课程表、考试安排等上方的选项后，在直接点叉后置顶就消失了… 希望能改进，非常实用的小程序，手动点赞！

---
**用户信息**
用户名：TBWYL（本科生-刘世缘-2015214142）
手机型号：iPhone 6s<iPhone8,1>（ios - 375x603）
微信版本号：6.5.3
We重邮版本号：v0.1.1

![img](http://wecqupt.congm.in/Ftvf60bpDM3_MN7QXsFJ-X4ktt5C?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/V2Xph43pgq4=/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

![img](http://wecqupt.congm.in/FsZuTogTFzVSUR-GWgLu2donxrkS?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/V2Xph43pgq4=/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

![img](http://wecqupt.congm.in/Fifwm19YLoZBLrC3BTAfl8LFT1Vk?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/V2Xph43pgq4=/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

![img](http://wecqupt.congm.in/Fr3ThnAUsob-TopYXnMp7FifhawW?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/V2Xph43pgq4=/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

**Comment by mcc108** [comment]
置顶这个是微信控制的，我们控制不了哦
