### ISSUE TITLE
【康康】一卡通余额

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#303]
一卡通余额更新了有延迟啊，还是显示的昨天的余额，要是能即时更新卡内余额就好了。

---
**用户信息**
用户名：康康（本科生-曾思康-2015210501）
手机型号：HUAWEI SC-UL10（android - 360x532）
微信版本号：6.5.3
We重邮版本号：v0.1.1

**Comment by mcc108** [comment]
目前的一卡通数据是无法做到即时同步的，因此会有一些延迟。
