### ISSUE TITLE
【ssacpklnm】考试安排刷新不了

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#304]
如题，另外一样能在小程序中充值一卡通

---
**用户信息**
用户名：ssacpklnm（本科生-张宇星-2016210609）
手机型号：SM-G9350（android - 411.42856x659.4286）
微信版本号：6.5.3
We重邮版本号：v0.1.1

**Comment by mcc108** [comment]
充值一卡通目前还有接口，可能暂时无法实现
考试安排下个版本在增加手动刷新
