### ISSUE TITLE
【singularity】建议

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#305]
一卡通不可以微信支付吗

---
**用户信息**
用户名：singularity（本科生-杨鑫玄-2015210136）
手机型号：M688C（android - 360x567）
微信版本号：6.5.3
We重邮版本号：v0.1.1

**Comment by mcc108** [comment]
目前不可以哦，这个是需要学校一卡通的中心提供支持的，目前是没有对应的充值接口。
