### ISSUE TITLE
【突围】建议去掉模糊搜索

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#311]
建议去掉模糊搜索，我不想被别人知道名字后知道我的课表学院学号，这是我的隐私。

---
**用户信息**
用户名：突围
手机型号：MX4 Pro（android - 384x567）
微信版本号：6.5.3
We重邮版本号：v0.1.1

**Comment by mcc108** [comment]
你好，这些内容都是在教务在线中可以查到的，我们只是做了搬运工。
即使我们去掉了模糊搜索，在教务在线上还是能通过名字知道您的课表学院学号的。
