### ISSUE TITLE
【这是昵称】新增反馈记录列表

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#312]
将在下一个版本新增反馈记录列表，能即时看到反馈动态。

---
**用户信息**
用户名：这是昵称（本科生-闵聪-2013211664）
手机型号：iPhone 6（devtools - 375x627）
微信版本号：6.3.9
We重邮版本号：v0.1.1

**Comment by mcc108** [comment]
测试评论

**Comment by mcc108** [comment]
该功能已成功上线，希望大家能通过此功能即时看到反馈动态。
该功能已成功上线，希望大家能通过此功能即时看到反馈动态。
