### ISSUE TITLE
【小戴】建议

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#314]
软件用起来很方便，界面也很不错，要是可以查到自己的学分情况那就更好了。尤其是任选和限选

---
**用户信息**
用户名：小戴（本科生-戴林甫-2015210985）
手机型号：m1 metal（android - 360x567）
微信版本号：6.5.3
We重邮版本号：v0.1.1

**Comment by mcc108** [comment]
以后如何能实现的话，我们会考虑加上学分详情的
