### ISSUE TITLE
【傻傻傻傻傻啊】网络错误

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#315]
查询别人考试的时候显示网络错误

---
**用户信息**
用户名：傻傻傻傻傻啊（本科生-贺晶华-2015214352）
手机型号：ONEPLUS A3000（android - 360x568）
微信版本号：6.5.3
We重邮版本号：v0.1.1

**Comment by mcc108** [comment]
大概是网络不太好，现在还是有这种情况吗？
