### ISSUE TITLE
【田辉】添加桌面图标问题

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#316]
添加到桌面失败（显示已添加但桌面没有）

---
**用户信息**
用户名：田辉（本科生-田辉-2014210721）
手机型号：GN8001（android - 360x567）
微信版本号：6.5.3
We重邮版本号：v0.1.1

**Comment by mcc108** [comment]
这个是微信的一个BUG，以后它们应该会修复掉的
