### ISSUE TITLE
【Terms】一卡通余额没有每天更新嘛？

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#321]
今天已经是1月10号，一卡通余额还是显示的1月8号第一次绑定的余额。而且，我已经对一卡通进行过充值。

---
**用户信息**
用户名：Terms（本科生-王杰-2015212846）
手机型号：OPPO R7（android - 360x567）
微信版本号：6.5.3
We重邮版本号：v0.1.1

![img](http://wecqupt.congm.in/FtI9aXkp-czoog3YjB0-i8VDmaqM?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/V2Xph43pgq4=/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

**Comment by mcc108** [comment]
一卡通的数据目前是有一定的延迟哦，以后应该会有一定改善的
