### ISSUE TITLE
【Sher】一卡通功能

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#327]
能否查询坐公交的余额呢？能充值更好辣！

---
**用户信息**
用户名：Sher（本科生-夏烈康-2013213825）
手机型号：Letv X500（android - 411.42856x659.4286）
微信版本号：6.5.3
We重邮版本号：v0.1.2

**Comment by mcc108** [comment]
坐公交的余额吗？抱歉应该不能查的哦~
