### ISSUE TITLE
【并不能愉快地划水】桌面小红点

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#328]
建议取消咨询更新后桌面小红点提示 ，几乎没有学生去看，强迫症受不了

---
**用户信息**
用户名：并不能愉快地划水（本科生-程宇飞-2014211785）
手机型号：ZUK Z2131（android - 360x572）
微信版本号：6.5.3
We重邮版本号：v0.1.2

![img](http://wecqupt.congm.in/FiFoOHuZsYcYkp4G53tG9Ban3g53?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/V2Xph43pgq4=/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

**Comment by mcc108** [comment]
我们并没有对We重邮设置桌面小红点提示，而且其他的用户也并没有这种情况。
我认为这是微信的消息提醒，在你的机型上错误的标记到了小程序身上，这应该是属于他们的bug吧。

**Comment by mcc108** [comment]
微信那边应该会在以后修复掉这个问题的。
