### ISSUE TITLE
【谭广照】操作不方便

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#329]
左上角的×是直接退出小程序的，对于第一次使用可能有点疑惑，特别是华为用户用的是虚拟键的，更容易误操作。希望可以在小程序那里增加比如我去查了课表，我点左上角的×是回到小程序最开始的界面首页那里

---
**用户信息**
用户名：谭广照（本科生-谭广照-2016211446）
手机型号：FRD-AL00（android - 360x526）
微信版本号：6.5.3
We重邮版本号：v0.1.2

**Comment by mcc108** [comment]
感谢反馈，但这是微信官方对小程序的设定，我们也没有办法的改变它。
