### ISSUE TITLE
【飘雪】信息有误

### ISSUE THREAD

**Issue by lanshan-admin** [lanshan-studio/wecqupt#330]
我是周青老师，但是课表和考试安排等内容都是周青华老师的，估计是弄混了，其他信息有没有弄混还不清楚，望能查一下，谢谢！

---
**用户信息**
用户名：飘雪（教职工-周青-030408）
手机型号：Che1-CL20（android - 360x567）
微信版本号：6.5.3
We重邮版本号：v0.1.2

![img](http://wecqupt.congm.in/FsHYgkvO52xsqkY889uxFR-9ljoF?imageView2/2/w/750/interlace/0/q/88|watermark/2/text/V2Xph43pgq4=/font/5b6u6L2v6ZuF6buR/fontsize/500/fill/I0VGRUZFRg==/dissolve/100/gravity/SouthEast/dx/10/dy/10)

**Comment by mcc108** [comment]
老师，您好我们已经查到这个情况。#294
是因为统一认证号和教务在线数据没有关联导致的，目前重名教师的一些教务数据就会出现一些问题。我们会在后续版本解决掉这个问题的。
现在我们已经提前将您的数据更正为正确的，请您核实一下。
