### ISSUE TITLE
【惠鸿飞】添加不了桌面

### ISSUE THREAD

**Issue by lanshan-admin** [Lanshan-Studio/wecqupt#358]
无法将快捷方式添加到桌面

---
**用户信息**
用户名：惠鸿飞（本科生-惠鸿飞-2014210553）
手机型号：PRO 6（android - 360x570）
微信版本号：6.5.4
We重邮版本号：v0.1.2

**Comment by xiaoliuhao** [comment]
这个可以看下手机有没有给微信创建桌面快捷方式的权限
