### ISSUE TITLE
【栗谷】图书馆还书

### ISSUE THREAD

**Issue by lanshan-admin** [Lanshan-Studio/wecqupt#374]
已经还书，但是显示还未还，信息不准确

---
**用户信息**
用户名：栗谷（本科生-杨璐-2016211467）
手机型号：MX4（android - 384x567）
微信版本号：6.5.4
We重邮版本号：v0.1.2

**Comment by xiaoliuhao** [comment]
同学,请问是最近还的书还是说很早就还了的呢
