### ISSUE TITLE
【机yui】申请教室

### ISSUE THREAD

**Issue by lanshan-admin** [Lanshan-Studio/wecqupt#375]
希望在查询空教室里可以申请教室。

---
**用户信息**
用户名：机yui（本科生-谭小龙-2016214210）
手机型号：FRD-AL00（android - 360x526）
微信版本号：6.5.4
We重邮版本号：v0.1.2

**Comment by xiaoliuhao** [comment]
感谢你提出的宝贵建议,我们会考虑添加这个功能的~
