### ISSUE TITLE
【空想家】个人信息中学院名称有误

### ISSUE THREAD

**Issue by lanshan-admin** [Lanshan-Studio/wecqupt#377]
如题

---
**用户信息**
用户名：空想家（本科生-覃朝晖-2016213171）
手机型号：SM-G9350（android - 411.42856x659.4286）
微信版本号：6.5.4
We重邮版本号：v0.1.2

**Comment by xiaoliuhao** [comment]
同学, 你在信息门户和教务在线的信息确实不一样,我们会帮你向老师反映的~ 建议你也多关注下信息门户,没改过来的话需要及时找老师反映
