### ISSUE TITLE
【薛磊啊！】咨询

### ISSUE THREAD

**Issue by xiaoliuhao** [Lanshan-Studio/wecqupt#526]
做得太好了，请教开发人员，后台是自己部署的吗？另外数据集是学校官方提供的吗？？？

**Comment by xiaoliuhao** [comment]
你好，后台为自己部署。数据方面有的是自己采集，有的是校方提供

**Comment by mcc108** [comment]
@xiaoliuhao   哈哈哈，看起来你在自言自语。 @lanshan-admin 不能用了么？
