### ISSUE TITLE
测试-JJ_Peng

### ISSUE THREAD

**Issue by wupengju** [lanshan-studio/wecqupt#63]
## 1.借阅信息
> **历史借阅和当前借阅不能点击查看借阅书籍的列表——不知道是不是需求没有定义**
## 2.公告
> **头条没有推荐的信息展示，显示空列表，是否可以考虑没有推荐信息就不做展示还是默认在没有推荐信息的情况下推荐的是教务公告的内容**
![screenshot_2016-11-30-13-44-37-738](https://cloud.githubusercontent.com/assets/16716231/20741913/22cc5960-b708-11e6-8305-52bb20d90c6a.png)
## 3.课表查询
> **课表UI显示有问题，是否可以考虑单屏显示五天的课表，单屏上显示了第六天的一半...**
![screenshot_2016-11-30-13-34-22-280](https://cloud.githubusercontent.com/assets/16716231/20741916/29b39f22-b708-11e6-81d6-e900e293460c.png)
## 4.空教室查询
> **选择周的横向列表，不能滑动~~~**

**Comment by mcc108** [comment]
1.借阅信息：只能查询当前借阅，不能查询历史借阅（没这个数据）
2.公告头条：后台接口正在写推荐为头条的算法
3.课表查询：UI故意设计为5天半，这样能一眼看出可以左右滑动查看周末的课表。（如果设置为5天整的话，应该会有一些用户不知道可以左右滑动的）
4.空教室查询：这个我提交新的issues了，我这会解决一下 - #65（https://github.com/lanshan-studio/wecqupt/issues/65）

**Comment by mcc108** [comment]
#65 DONE （将会在milestone v0.0.6版本更新）

**Comment by wupengju** [comment]
@mcc108 好吧，课表查询可以考虑一下就是在进入当前页面的时候 弹窗或者动态提示一下"往左滑动可以查看周末课表" 在一定时间延迟后消失，实在是有强迫症的人看着真的有点... 只是建议  闵神吊吊的
