### ISSUE TITLE
【测试报告】手机型号：NX507J，设备名称：nubia z7 mini

### ISSUE THREAD

**Issue by su-dan** [lanshan-studio/wecqupt#70]
### 课表页面
1. 页面下方周数左右按钮没作用；
2. 详情卡片动画有点卡顿，不知道是不是我的手机问题

### 成绩查询
1. 可能当前没有成绩，但是会有弹窗，弹窗信息是”未知错误“，感觉如果是没有成绩显示没有成绩之类的比较好吧
![screenshot_2016-11-30-18-54-04](https://cloud.githubusercontent.com/assets/14104060/20750217/a9ce490a-b730-11e6-871b-8437fd0c20f7.png)

### 学生查询
1. 搜索改成一个按钮感觉比较直观，就两个字感觉不太那个

### 一卡通
1. 偶尔打开一次，折线图有向下移位的效果，就是折线图不在原来的位置上，查看详情的竖线会高一截，但是点击折线图查看详情就会恢复原位。但是刚刚测试一遍又没有这个问题了。。。奇怪。
![screenshot_2016-11-30-19-05-33](https://cloud.githubusercontent.com/assets/14104060/20750208/a236ef26-b730-11e6-903e-853d57214a4d.png)

### 资讯
1. 资讯的加载圈圈好像其他页面的五颜六色的圈圈不一样，是不是故意这样子的哇
![screenshot_2016-11-30-19-12-03](https://cloud.githubusercontent.com/assets/14104060/20750322/2368f1d4-b731-11e6-8198-5938ef08c06e.png)

**Comment by mcc108** [comment]
#### 课表页面
1. 那个按钮只是一个样子，只不过也可以加上tap的效果： #71
2. 动画有点卡顿，下个版本我hack了GPU加速，不知道能不能好点。如果还是卡，只能看微信小程序那边以后更新能不能好转。不能好转就不要动画了

#### 成绩查询
接口和数据还有问题

#### 学生查询
新建一个issues我来解决 #72

#### 一卡通
我也是有这个问题，不知道是什么情况...  我没找到解决方案

#### 资讯
资讯加载是微信自带的那个加载笼罩层， 主要是存在不断向下滚动翻页的情况，就没地方显示圈圈的加载了。
所以就用微信自带的那个加载笼罩层

**Comment by xiaoliuhao** [comment]
我觉得折线图那里可以弄成每次消费金额的折线图好一点 ， 像我这种一次充值一月消费的  一直是一条下滑线……

**Comment by mcc108** [comment]
@xiaoliuhao 之前设计是给的消费金额，  但这些的话  充值就不能展示了...

**Comment by mcc108** [comment]
@su-dan DONE  #71 &  #72
