### ISSUE TITLE
【内测报告】Zane96

### ISSUE THREAD

**Issue by Zane96** [lanshan-studio/wecqupt#78]
+ 绑定账号的时候，添账号的时候输入法把密码栏都挡住了，建议这个时候整体View上移
+ 登陆完了之后没有自动刷新首页，还需要用户手动刷新
+ 加载的ProgressBar动画卡顿明显
+ 加载单个课信息的时候，卡顿太明显了。。。
+ 显示了单个课详细信息的时候我按返回键直接退到首页了，建议应该是返回键之后把底下这个弹出拦隐藏
+ 考试信息只能查最近的一门考试
+ 报修那个模块，申报的页面，最下面那个输入框，我点一下，输入法直接把它盖住了，用户输入的时候都不看到输入框
+ 更多->头条，是没有数据嘛？还是？。
+ 更多模块里面。用户先上拉刷新了之后，建议再下拉刷新之后把我之前加载了的别弄没了（又要重新上拉加载）。
+ 更多模块里面，建议最上面的一条选择bar，建议不要在用户向下滑的时候消失了，不然用户换的时候还要再刷最上面去。或者向下滑的时候这个Bar立即出现也可以（做成浮动框，响应滚动事件）。

**Comment by mcc108** [comment]
1、这个是微信小程序的这样设定...   感觉我们也没办法..
2、创建了新的issues，我一会解决下.. #80
3、卡顿的问题是微信渲染得不够好..   电脑上测试就挺正常的。
4、课表里面有些动画卡顿是有这个问题，如果微信后续更新不能改善的话，就只有考虑去掉动画了.. #81
5、控制不了上面的返回键的事件...  微信做了限制，只能设置上面的颜色和文字。
6、考试信息，你的教务在线上面好像只有一门：https://jwzx.cqupt.congm.in/jwzxtmp/showKsap.php?type=stu&id=2014210876
7、同上..   输入法这个问题是微信搞的，我们控制不了，我们能做的比较局限
8、资讯头条，正在写推荐算法，见 #69 
9、应该是资讯模块吧，上拉刷新相当于是重新加载了这个页面，是为了防止一直往下拉导致页面太累赘了，然后重置一下
10、这个问题创建了新的issues来解决下.. #82
