### ISSUE TITLE
【内测报告】-灿。

### ISSUE THREAD

**Issue by LuoYangCan** [lanshan-studio/wecqupt#79]
* 登陆，点击完善信息之后回到主页面没有马上刷新，要下拉刷新后才显示个人信息。
* 如果课表下方的周数能点开然后选择周数就好啦~
* 学生查询如果能在右侧添加清空按钮，能在键盘端点击搜索就好啦
* 一卡通似乎没有及时更新啊。。还是27号的
* 学术讲座第一条文字间有一点乱码（似乎不是小程序的锅
* 似乎每一次登陆都要完善信息

**Comment by mcc108** [comment]
1、已发现这个BUG #80 
2、下方的周数目前是左右滑动，如果有这个需求的话，我建个issues有空了解决下：#84
3、我尝试解决一下 #85
4、一卡通的数据是不能即时更新的...  以后再协调解决下这个问题
5、这个后端接口可能需要优化一下 @xiaoliuhao 
6、是吗...  我验证一下
