### ISSUE TITLE
【内测报告】D-9133

### ISSUE THREAD

**Issue by ChenTomoe** [lanshan-studio/wecqupt#85]
### 登录
- 没有找回密码链接，在帮助中的忘记密码？下可以做两个进入统一身份认证平台的链接，分别为使用内网外入进入和非使用内网外入进入（比如手机连着CQUPTwifi可以直接进入平台）
- 完善信息的时候没有把输入框上移，每输入一次信息要收起输入法才能点击到下一个输入框
- 输入的密码显示出的点太大了
### 课表
- 按学期查询课表没有显示课程上课是从哪一周到哪一周，想截图保存留以后看都不行；点开我的电工电子课程的时候，这门课有两节，点开之后的两个重叠页面不能滑动切换，物理实验可以滑动切换，但是切换过程不够迅速（可能我的网速卡吧QAQ）；数据结构实验课在总课表上显示是9-11节，但是点开课表时小卡片页面显示的是9-10节；点开点解课表后总课表的透明度太低了，糊的看着好难受；任选课程不是分人文和任选的嘛，课表查到的课程性质都是任选（教务在线的成绩总表中也是这样，只有选课的时候有人文和任选区别的标注）
- 按周查询课表，切换下一周不能滑动切换，建议字体改小一点，让一周的课表页面宽度不超过手机自身的宽度；用来显示现在上什么课的那个横条看着好奇怪，建议将正在上的那节课单元格改一下别的样式以示提醒
### 成绩
- 只能查到大一下学期的成绩，而且查不到卷面成绩，也没有绩点和排名
### 空教室
- 选择周几那一栏在我手机里周末显示到SU，就一个N没有显示出来，看着好难受（可能是因为我的手机显示屏比较大，6.44寸），建议将四个选项使用下拉列表
### 学生查询
- 搜索框不明显，点进去我以为是一个空白页面
- 输入完毕后回车键不能直接搜索
### 一卡通
- 建议一卡通模拟成校园一卡通的样子而不是银行卡，颜色选用一卡通主体颜色应该会更好看一点
- 近10次消费情况的折线图建议纵坐标改为消费金额，使用余额做纵坐标的时候标注一下纵坐标含义，刚点进去我都没有看懂这个表
### 借阅
- 没在图书馆借过书，体验不到，恍恍惚惚
### 学费
- 加载失败...
### 电费查询
- 查不到欠的电费总额
### 报修
- 前几天打电话报修的，完了之后发短信说“如果您通过网络报修，可以登录系统进行评价”，咱这个没有评价的选项呀
### 教务公告
- “点击预览”的按钮执行的是下载操作

**Comment by mcc108** [comment]
#### 登录
1、找回密码链接：微信小程序官方目前没有办法打开外部网页链接或调出浏览器，以后官方支持了再尝试解决。
2、这个也是小程序官方的坑...  不能设置..  调出输入法是它实现的
3、输入的密码显示出的点也是小程序默认的 - -

#### 课表
1、显示课程上课是从哪一周到哪一周，这个放在表格里面可能放不下（有的课上课的周次很长），只能点开在详情里面才能看到；
2、两个课重叠时的样式和三个课重叠时的样式不一样，目前三个课重叠是可以左右滑动的，两个课重叠是通过点击实现切换，这个问题在 #62 中，我会尝试让两个课重叠时也能左右切换；
3、切换动画卡顿的问题，看微信官方能否改善。如果微信后续更新不能改善的话，就只有考虑去掉一些动画了 #81
4、三节连上这个，我新建一个issues来解决：#86
5、看着太糊，意思是笼罩层再加黑一点嘛？ #87
6、任选这个，因为数据是教务在线来的，它那边显示是什么，我们这边只能显示什么
7、切换周数只能通过下面切换，字太小可能会看不清，我们是按照一屏5.5节课设计的，这样能看到周6的一半，用户就知道能左右滑动看周末了。
8、那个横条会随着时间的流逝移动的....   刚开始上课会在开头，上到一半会在中间，休息时间会一直停留。

#### 成绩
这个是从外网教务处网来的数据，内网教务在线的数据暂时还不能获取，以后看能不能通过和那边沟通来获得这个数据

#### 空教室
这也是故意设计的露出一半，表示可以左右滑动..... 逼死强迫症了么..  6.44 小米max?

#### 学生查询
首屏好像是应该多一点提醒 #88
回车不能搜索已发现，我一会解决  #84

#### 一卡通
1、下个大版本，一卡通再改版完善下
2、这个应该有 #89

#### 学费
你的一卡通号是什么呢，我看一下是什么问题

#### 电费
绑定了寝室吗？查不到是指什么呢，有没有图
如果显示正常，只是数据，是因为数据还没更新...

#### 报修
评论做起来可能又得多花时间，以后的版本做~

#### 教务公告
预览就是下载了才能预览..

**Comment by ChenTomoe** [comment]
课表-5：是这个意思，比如手淘，有未布满全屏的页面显示时原页面是用黑色然后调透明度
课表-8：我知道那个是随着时间下移的，但是看着有点不习惯吧，估计新用户不能看到就GET到这个点
- 空教室：在我的手机上我觉得可以改变一下字体或者间距不让它滑动了，逼死强迫症的节奏（吐血ing），6.44小米MAX√
- 一卡通-2:我是想说纵坐标可以使用消费金额，这样就可以看到近期10次消费的金额，明显的看到自己的花销。不过这样可能要改后台的数据吧，所以如果继续使用卡内余额做纵坐标最好就标注一下纵坐标的含义，比如物理上的图标没有标注谁知道是v-t图像还是x-t图像呢(∩_∩)
- 学费：又去看了一下，还是查不到，我的一卡通：1644064
- 电费：我的意思是电费只能查到本月用电度数和一个金额，没有说明这个金额是这个月的消费金额还是什么。我建议的是显示累计欠了多少，比如你去圈存机交电费，账户余额会显示例如“-50”的字样，意思是这个寝室已经欠了50块钱电费了
- 教务公告：教务在线也是直接下载附件，可以把点击预览改为点击下载，当然，如果我们能做出来像QQ那样小的word文件可以不下载直接预览更6了
- 附：学长学姐好棒，像大神学习orz @mcc108

**Comment by mcc108** [comment]
@ChenTomoe
课表-5 ，下个版本应该改好
课表-8，习惯了就会觉得挺好用的哈哈0 。0
空教室，在所有手机上都是只露一半...
一卡通，消费金额和话，可能充值就看不了了，一卡通打算下一个大版本改版下
学费查不到，后端看一下 @xiaoliuhao
电费：放到 #92 一起处理
教务公告：本来是支持一些后缀的预览的，只是逻辑没写好，出现bug了， #90 下个版本修复下
