### ISSUE TITLE
【内测报告】Houskii

### ISSUE THREAD

**Issue by houskii** [lanshan-studio/wecqupt#91]
测试手机：iPhone6 
OS版本：10.0.1
微信版本：6.3.31
测试环境：wifi

【Bug】
- 资讯界面 OA公告 加载失败，弹窗：request:fail exceed max task count
- 资讯界面 版块频繁切换/We重邮频繁登入登出，触发多次弹窗： request:fail 请求超时
- 空教室 十六周-MON-7-8节-三教/四教 加载失败，弹窗：位置错误
- 退出登陆 多次切换用户后 完善的信息会被抹去（？）
- 一卡通界面 近10次消费情况的图发生错位
- 课表查询 20周以后无日期

【建议修改】
- 完善信息界面 寝室号 输入字母依然成功通过，并引发电费查询界面 未知错误
- 完善信息 未完善寝室楼栋依然成功通过
- 网络不佳条件下，功能界面白屏
- 资讯 退回到 首页，容易习惯性右滑直接退出
- 身份证后6位输入错误导致 取数据时 未知错误
- 身份证后6位强制输入数字，可能会导致X无法输入的问题
- Loading动画过于卡顿
- 登陆/完善信息/切换绑定 按钮位置偏下
- 课表查询 无法直接切换周数/总课表
- 课表查询 页面逻辑有待改善
    - 课表查询打开学生查询，学生查询返回，直接回退到主界面
    - 课表查询打开学生查询，学生查询打开课表查询，课表查询返回，直接回退到主界面

**Comment by houskii** [comment]
github好像不支持直接发图
[图：多次弹窗](http://ww3.sinaimg.cn/mw690/721ad027gw1fablxb8q28j20ku112t9z.jpg)
[图：一卡通错位](http://ww1.sinaimg.cn/mw690/721ad027gw1fablx9v60hj20ku112adf.jpg)

**Comment by mcc108** [comment]
@houskii   github发图是把文件拖动到输入框里面就可以了
然后markdown的发图是`![说明](图片url)`

**Comment by mcc108** [comment]
#### Bug
1、资讯界面， 频繁切换的BUG是微信小程序官方没有处理好..  微信小程序目前还有很多自带的BUG和坑，我尝试看能不能在进行下一个操作时终止掉上一步的网络请求。 #95 
2、空教室这个我好像没出现问题也
3、来回切换用户后，完善的信息就会抹去，这个问题看后台能不能把一卡通用户和完善的信息绑定下.. @xiaoliuhao 
4、一卡通界面 我手机上也有错位，不知道为啥，奇怪的微信小程序，当成BUG，看以后小程序官方更新后能不能解决吧..    #99
5、新建一个issues，二十周无日期 #98

####建议修改
1/2、寝室号禁止输入字母，未选择寝室楼栋就不能只提交寝室号 #100
3、网络不佳时各页面的提醒 #101
4、这个微信小程序限制了，不能进行设置....
5、错误的身份证后6位导致查询成绩时报错 @xiaoliuhao 
```
Notice: Undefined variable: td_array in /home/lanshan/web/wecqupt/server/api/get_kscj.php on line 80

Warning: array_shift() expects parameter 1 to be array, null given in /home/lanshan/web/wecqupt/server/api/get_kscj.php on line 40

Warning: Invalid argument supplied for foreach() in /home/lanshan/web/wecqupt/server/api/get_kscj.php on line 42
```
6、身份证后6位无法输入X   #102
7、Loading动画卡顿是微信小程序的锅..  它很多动画都没优化好...  原图挺正常的， 电脑上调试这些页面也挺正常的- -
8、登陆/完善信息/切换绑定 按钮位置上移一些  #103
9、无法直接切换是指什么呀，不是右下角的切换嘛？
10、主要是防止相互打开导致页面太多至崩溃，之前在#73 #74 有提到

**Comment by houskii** [comment]
@mcc108 9.无法切换，比如说第十三周直接切换到第一周？
查看总学期的课表，滑动下面的课程详细栏，会导致背后的课表一起滑动（滑动穿透？）

其实那个寝室的号设置的应该是输入数字，因为点开弹起的是数字键盘，但是可以通过粘贴板把英文/符号贴过去，建议在提交的时候和身份证后六位一起本地确认一下

**Comment by mcc108** [comment]
@houskii  9、之前他们也提出过这个问题，但又有人说没有必要，见 #83 ，这个看用户反馈的需求量大不

滑动穿透 ..  还有这种BUG？我手机上就没有也...

嗯嗯寝室号应该再用js判断一下的
