### ISSUE TITLE
【内测报告】sdoasddd0921

### ISSUE THREAD

**Issue by sdoasddd0921** [lanshan-studio/wecqupt#94]
* 进入程序的时候加载有点小慢
* 没有找回密码的连接（第一次登忘了密码想找回但是发现木有找回密码）
* 一卡通余额和电费延迟有点严重，感觉如果查的不是当时的结果就没什么用
* 从上方的功能键点进功能的时候，有的功能加载的时候那个加载的圈很卡，看着不舒服
* 成绩只能查上一学期的，想查更久以前的查不了
* 学费查询点进去就弹窗加载失败，业务保修点进去加载很久，然后也弹窗失败
* 反馈和关于We重邮点进去一片绿色，什么东西都没有
* 咨询里的头条没有信息，只有3条空白的彩色横条，向上划还能加载出更多的彩色横条，都是3个一组的
* 界面设计的很好看，课表做的很不错
* 感觉就余额和电费不是当时的结果这点很不实用，其他问题都是小问题

**Comment by mcc108** [comment]
1、只有等微信小程序官方来优化这个问题了...
2、找回密码可以在绑定页面的“帮助”中找到其链接。因为微信小程序官方目前没有办法打开外部网页链接或调出浏览器，所有不能实现有链接跳转。
3、电费问题好像解决了，是最新的了（上个月），等待更新就行了。一卡通余额大概需要去沟通一下。
4、加载的圈原图和电脑上测试都很正常的，在小程序上就有点卡了，看微信自己以后能不能优化掉，不然就再想办法解决    #105
5、目前数据成绩只能查上一学期的，想查更久以前的查不了。以后的版本再解决掉 @xiaoliuhao 
6、学费查询点进去就弹窗加载失败，业务保修点进去加载很久，然后也弹窗失败；后台看看 @xiaoliuhao 
7、反馈和关于这两个页面还没有做，见 #67 #68 
8、资讯的头条正在写推荐算法 见 #69

**Comment by xiaoliuhao** [comment]
#### 成绩
成绩因为是现在在教务处抓的嘛 , 所以没有往年的数据, 以后如果能通过数据库查询的话 , 就有很久以前的了 ,
#### 学费查询大二的已修复 , 业务报修因为请求时间较长, 虽然做了缓存,但是第一次访问可能会超时报错, 第二次访问会变快,
