### ISSUE TITLE
【内测报告】fbl861543

### ISSUE THREAD

**Issue by fbl861543** [lanshan-studio/wecqupt#96]
登录
1. 切换账号的时候输入的账号和密码都是正确的，但显示错误
2.可以将输入框设计为输入正确的用户名位数之后键盘自动收回吗？感觉现在的输入体验不是很
3.帮助那一栏为啥账号那有一个句号占了一行，可以把句号删了吗？
4.反馈那一项点击进去后是空白的
5.关于那一栏点进去也是空白的

课表
1.点单节课具体的信息显示的时候感觉有点卡
2.学生名单里没有显示专业名

成绩查询
1.成绩查询只可以查询大一下的，而且不能显示专业排名和绩点

考试安排
感觉这个挺好用的

空教室
空教室查询可以增加一个选项吗？教室能够容纳多少人

一卡通
1.感觉一卡通的图片不是很好看
2.可以把“点击上图查看对应消费详情”做的明显一点吗？
3.更新好慢，今天已经12月1号了，可是消费情况还是11月29号的

学费信息
加载失败

电费查询
现在已经12月1号了电费还是7月25号的

物业报修
填报修申请的时候已经填了服务项目、类型、区域等，申报内容就不需要了吧

资讯
1.头条里面为什么都加载不出来404错误
2.学术讲座中打开有的只有标题，内容是空的（重庆邮电大学第十一届研究生论坛讲座）

**Comment by mcc108** [comment]
#### 登录
1、不是吧0.0 @xiaoliuhao 肯定帐号或密码错了吧
2、这个可以有，正好就是觉得微信小程序的输入框有点影响用户体验，你的这个点子应该可以实现的，正好解决的这个问题。😄 #108
3、去掉帮助里的句号 #110
4/5、反馈和关于页面优先级较低，还没有完成 #67 #68

#### 课表
1、动画卡顿已知，具体见#81
2、无专业名，这个问题已知，见 #69  @xiaoliuhao

#### 成绩查询
 目前数据成绩只能查上一学期的，想查更久以前的查不了。以后的版本再解决掉 @xiaoliuhao

#### 空教室
教室的容量 我们的接口里面好像没有这个数据 @xiaoliuhao  有吗？？

#### 一卡通
下个大版本，一卡通再改版完善下
一卡通数据有点延迟，大概2~3天...

#### 学费信息
又一个加载失败的 ..   @xiaoliuhao

#### 电费查询
数据将在近期更新 

#### 物业报修
申报内容通常是具体的描述呀。

#### 资讯
1、资讯的头条正在写推荐算法 见 #69
2、学术讲座中打开有的只有标题，内容是空的（重庆邮电大学第十一届研究生论坛讲座）   后台看看@xiaoliuhao

**Comment by xiaoliuhao** [comment]
###空教室
教室容量暂时没有,不过可以在教务在线抓,我找到了链接刚才 http://jwzx.cqupt.edu.cn/jwzxTmp/showEmptyRoomResult.php?zc=13&xq=2&sd=12

###课表
专业名是有的 , 之前字段是 zy 现在修改为zym

###学费信息
大二同学无法查询学费的问题已经修复

###资讯
编码问题 已修复
