### ISSUE TITLE
【内测报告】AaronWharton

### ISSUE THREAD

**Issue by AaronWharton** [lanshan-studio/wecqupt#97]
- 其他问题他们都提到了，没怎么玩微信，不了解微信小程序这方面。就一个小问题，这个能在桌面建一个类似快捷方式的东西么。表示我是每次都是扫码进入应用的😭太麻烦。

**Comment by mcc108** [comment]
@AaronWharton 桌面快捷方式这个以后微信会有这个的，而且还有微信的固定入口，目前微信还没有正式发布小程序，以后微信为了推广小程序这种方式会让用户更方便了。

**Comment by AaronWharton** [comment]
噢，这样~
